### ISSUE TITLE
Question for 'inflatecollisionintervals' parameter

### ISSUE THREAD

**Issue by hyunseok-yang** [PathPlanning/AA-SIPP-m#14]
Hi, 
I got a one concern while studying multi-agent path plannig based on your work.

README.md says '<inflatecollisionintervals>' is increasing **the time** between the moments when the agent and the dynamic obstacles (or high-priority agents) pass through the same areas of the space. 

But, according to this (paper)[https://arxiv.org/pdf/1906.06911.pdf] and code, 'infaltecollisionintervals' looks kind of size handling not a time domain.

Could you explain the parameter what you intended.

```c++
double r(constraint.size + agentsize + inflateintervals); //combined radius
```

**Comment by aandreychuk** [comment]
This value is used for collision checking formula. It checks whether there is a time moment when the distance between agent and constraint is less than 'r'.

If the required distance between constraint and the agent is inflated, the agent will be passing the same areas earlier/later than constraint.
