### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by sonytornado** [PathPlanning/AA-SIPP-m#3]
can I ask for a copy of demo source code in the video folder?

**Comment by aandreychuk** [comment]
What do you mean under "a copy of demo source code"?
The code of the algorithm is in repo and its publically available... Or are you looking for code that can visualize the resulting log-files?

**Comment by sonytornado** [comment]
Yes,I'm looking for code that can real time visualize the result

**Comment by sonytornado** [comment]
I download your source code, running it, but I got a error result. did I have mistake in agents goal 
setting?

pls looking at this log file in the attachment.
[all_in_one_example_log.zip](https://github.com/PathPlanning/AA-SIPP-m/files/4132635/all_in_one_example_log.zip)

**Comment by aandreychuk** [comment]
I see no errors in your log-file. I also tried to launch the input file and everything was ok.
There was only one warning about undeclared parameter, but it's not a problem.

If you wanted both agents to move through a narrow passage with 1 cell width - it is impossible in any graph based approach. Even with size 0.1 agents occupy the centers of grid cells, so as they both cannot occupy or move through the same cell at the same moment, one of them has to go in some other way. 

Here is the code of the visualizer. It's based on Qt Framework, so QtCreator is the only way how you can build and run it.
[src.zip](https://github.com/PathPlanning/AA-SIPP-m/files/4133025/src.zip)

**Comment by sonytornado** [comment]
How to guarantee safe interval distance between these two agents. At least, they must stopped face to face and can't crashed on themself.

**Comment by aandreychuk** [comment]
It is an offline planner, i.e. all trajectories are planned before the agents actually start to move. So in case when the algorithm cannot find any collision-free solution, agents will not stop face to face, you will just not recieve any solution. 

If solution is found it's guaranteed that it has no collisions. That means that the distance between the agents centers is never less than the sum of their radii.

Also note that in case of unsolvable tasks and using random rescheduling, the algorithm will be trying to shuffle the priorities and replan the trajectories until timelimit will not be exceeded.

**Comment by sonytornado** [comment]
Thanks a lot. It's good enough for me.
